version: 17
jobs:
- name: Sync to Github
  steps:
  - !PushRepository
    name: Push to github
    remoteUrl: https://github.com/billm/fancontrol.git
    passwordSecret: github-access-token
    withLfs: false
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
- name: Compile and Release
  steps:
  - !UseTemplateStep
    name: Compile and Release
    templateName: Compile and Release
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: main
    projects: fancontrol
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
  postBuildActions:
  - !RunJobAction
    condition: successful
    jobName: Sync to Github
stepTemplates:
- name: Compile and Release
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Compile
    runInContainer: true
    image: golang
    interpreter: !DefaultInterpreter
      commands:
      - go build fancontrol.go
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: Release
    artifacts: fancontrol
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
